config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
require_relative '../lib/domain_restrictor'

Rails.application.routes.draw do

  constraints DomainRestrictor.new  do

    namespace :admin do
      resources :users
      resources :domains

      root to: "users#index"
    end

    devise_for :users

    resources :domains do
      member do
        get :setup
        get :verify
      end
    end

    get :dash, to: "pages#index", as: :dashboard
    get :login, to: "pages#backdoor"
    get :gatekeeper, to: "domains#gatekeeper"
    root "pages#index"
  end

  constraints DomainRestrictor.new(false)  do
    get "/", to: "parking_lot#show"
    post "/", to: "parking_lot#offer", as: :offer
    patch "/", to: "parking_lot#offer"
  end
end

app/controllers/parking_lot_controller.rb
class ParkingLotController < ApplicationController
  layout "default"

  def show
    @domain = Domain.find_by_name(request.host)
    @enquire = Enquire.new
  end


  def offer
    @domain = Domain.find_by_name(request.host)
    @enquire = Enquire.new enquire_params
    @enquire.domain = @domain
    if @enquire.save
      @enquire = Enquire.new
      render :show, notice: "Your offer has been captured successfully."
    else
      render :show, alert: "There was an error. Please try again."
    end
  end

  private
  def enquire_params
    params.require(:enquire).permit(:email, :name, :notes, :offer, :phone)
  end

end

app/views/parking_lot/show.html.erb
<% content_for :title do %>
  <%= @domain.title %>
<% end%>

<% content_for :head do %>
  <%== @domain.head_scripts %>
<% end%>

<main class="w-full lg:h-screen flex flex-col lg:flex-row justify-center items-center">
  <div class="flex flex-col w-full lg:w-1/2 h-full justify-center items-center">
    <h1 class="text-6xl leading-tight flex flex-col items-center">
      <span class="font-bold"><%= @domain.name.titleize %></span>
      <span class="font-medium">available for sale!</span>
    </h1>
    <p class="text-gray-900 text-xl p-2">
      The owner of this domain has parked it at parkade.host
    </p>
  </div>
  <div class="bg-white w-full lg:w-1/2 h-full justify-center items-center flex flex-col">
    <h2 class="font-bold text-3xl">Interested in this domain?</h2>
    <%= form_for(@enquire, url: offer_path, html: { class: "w-full max-w-lg py-6" }) do |f| %>
      <div class="mb-4">
        <%= f.label :name, class: "font-medium"%>
        <%= f.text_field :name, placeholder: "John Doe", class: "w-full p-2 rounded border-blue-200 border-2 mt-1 outline-none" %>
      </div>

      <div class="mb-4">
        <%= f.label :email, class: "font-medium"%>
        <%= f.email_field :email, placeholder: "johndoe@example.com", class: "w-full p-2 rounded border-blue-200 border-2 mt-1 outline-none" %>
      </div>

      <div class="mb-4">
        <%= f.label :phone, class: "font-medium"%>
        <%= f.phone_field :phone, placeholder: "", class: "w-full p-2 rounded border-blue-200 border-2 mt-1 outline-none" %>
      </div>

      <div class="mb-4">
        <%= f.label :offer, class: "font-medium"%>
        <%= f.text_field :offer, placeholder: "Your offering price", class: "w-full p-2 rounded border-blue-200 border-2 mt-1 outline-none" %>
      </div>

      <div class="mb-4">
        <%= f.label :notes, "Comments", class: "font-medium"%>
        <%= f.text_area :notes, class: "w-full p-2 rounded border-blue-200 border-2 mt-1 outline-none" %>
      </div>
      <%= f.submit "Make An Offer", class: "px-4 py-2 bg-indigo-400 hover:bg-indigo-600 text-white w-full rounded" %>
    <% end %>
  </div>
</main>

<% content_for :footer do %>
  <%== @domain.footer_scripts %>
<% end%>